### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by Sargeanthost** [Kideneb/MinecraftMacroTool#3]
Exception in thread "main" java.lang.NullPointerException
	at logic.Macro.readLine(Macro.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at logic.Main.main(Main.java:42)

Happens randomly while starting and stopping macros

**Comment by Kideneb** [comment]
Did you get a message along the lines of "The file x could not be found" before?
If that's the case, you probably refer to a non-existing macro in one of your files.

**Comment by Sargeanthost** [comment]
Nope, still happens, completely random at when it happens. That's the exact stack trace.

**Comment by Kideneb** [comment]
Could you provide me with the macros you are executing, when the error occurs, so I can investiage further?

**Comment by Sargeanthost** [comment]
Sure, it happens to any macro I use; they're on a separate computer, so
expect a second email

**Comment by Sargeanthost** [comment]
Macro doesn't matter, anyone crashes randomly.

Error happens when pressing start

**Comment by Sargeanthost** [comment]
I'm closing because I've forked this project and have added numerous updates and fixes to exception handling.  I might submit a pull request when I'm satisfied with what features I've added.
